plugins:
  issue_comment.created: # or any other event
    - uses: # sequence of plugins to run
        - plugin: jordan-ae>/Unassign:compute.yml@development
          name: Unassign
          id: unassign-command
          type: github
          description: "Plugin description"
          command: "<regex for command>" # if applicable
          example: "<example usage>" # if applicable
          with: # below is an example, cater to your plugin's needs
            disabledCommands: []
            timers:
              reviewDelayTolerance: 86000
              taskStaleTimeoutDuration: 2580000
            miscellaneous:
              maxConcurrentTasks: 3
            labels:
              time: []
              priority: []
